---
apiVersion: v2
appVersion: v1.2.0
description: Mealie is a self hosted recipe manager and meal planner with a RestAPI backend and a reactive frontend application built in Vue for a pleasant user experience for the whole family.
name: mealie
version: 5.1.3
kubeVersion: ">=1.16.0-0"
keywords:
  - mealie
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/mealie
icon: https://raw.githubusercontent.com/hay-kot/mealie/gh-pages/assets/img/favicon.png
sources:
  - https://github.com/hay-kot/mealie
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
  - name: jonnobrow
    email: jonathan@jonnobrow.co.uk
  - name: cmartin616
  - email: cmartin616@gmail.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
